### ISSUE TITLE
Define CONFIG_MIL_DESC_MEM_ADDR is defined ?

### ISSUE THREAD

**Issue by EmbeddedRepublic** [Danoloan10/xm-sparc#1]
Hi Danolan

Where is CONFIG_MIL_DESC_MEM_ADDR defined ?

Many thanks
Younes

**Comment by Danoloan10** [comment]
Hi,

That is one of the defines generated by Kconfig. In order to build XtratuM, you have to first configure the build setting the appropriate variables in the xmconfig.sparc file. There, you have to set TARGET_CCPATH to the root of the SPARC compiler toolchain. You can configure flags and prefixes as well. Then, copy `xmconfig.sparc` to a file named just `xmconfig`, and you will be able to run `make menuconfig`. Go through the steps to configure all the three components, exiting each prompt to continue.  Then you may run make to build XtratuM with the configured toolchain.

I will add these build instructions in the README

Hope this helps :)

**Comment by Danoloan10** [comment]
You may find this information useful. Even though it's in Spanish, you may use some translator to read it.
https://github.com/Danoloan10/xm-ia32/blob/master/README.md

**Comment by EmbeddedRepublic** [comment]
Thank you Bro.
Let me know if you want to work in Switzerland. I might have a job for you.

Regards
Younes
